### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by michela** [orff/swiftScreenSaver#1]
Thanks for this sample. I've forked and upgraded this to work with Swift 3 but still struggling with syntax. 

I've set the SCNView options to nil here because couldn't get past this error

> Cannot convert value of type '[SCNView.Option : UInt]' to expected argument type '[String : Any]?'

https://github.com/modprods/swiftScreenSaver/blob/master/MySwiftScreenSaver/swiftSS.swift#L83

**Comment by orff** [comment]
Sorry, just noticedthat and the PR that fixed it. All merged in.

**Comment by orff** [comment]
PR fixed this issue and others.
